### ISSUE TITLE
Reporte Test Rail

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-balam#1]
[Reporte TestRail.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-calidad-de-testrail-con-wallet-balam/files/9698495/Reporte.TestRail.pdf)

**Comment by carlos-chrs** [comment]
calificado 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
